name: inclusichat
description: "Mensajería privada e inclusiva para conectar con libertad."
publish_to: 'none'

version: 1.5.1+44

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  http: ^1.2.2
  record: ^7.1.1
  audioplayers: ^6.8.1
  path_provider: ^2.1.6
  flutter_secure_storage: ^10.0.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_callkit_incoming: ^3.1.5
  uuid: ^4.6.0
  file_picker: 12.0.0
  camera: 0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/branding/inclusichat-logo-hd.png"
  min_sdk_android: 21
  adaptive_icon_background: "#121820"
  adaptive_icon_foreground: "assets/branding/inclusichat-logo-hd.png"
  windows:
    generate: true
    image_path: "assets/branding/inclusichat-logo-hd.png"

flutter:
  uses-material-design: true

  assets:
    - assets/branding/inclusichat-logo-hd.png
